version: '3.4'

services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: "eric"
    user: eric
    volumes:
      - ..:/workspace:cached
      - /opt/local/renv/cache:/renv/cache
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    
    command: sleep infinity
    network_mode: service:db

  db:
    image: mongo:3.4
    command: mongod --port 12335
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: testdb
    ports:
      - 12335:27017

  rstudiopreview:
    build:
      context: ./rstudio_docker
      dockerfile: Dockerfile
    container_name: rstudiopreview
    volumes:
      - /home/eric/shinydevseries_projects:/home/eric/shinydevseries_projects
      - /home/${USER}/.ssh:/home/${USER}/.ssh
      - /opt/local/renv/cache:/renv/cache
      - ${VOLUME_PATH}/.devcontainer/rstudio_config_dir:/home/${USER}/.config/rstudio
    restart:
      unless-stopped
    ports:
      - 4670:8787

volumes:
  mongodb-data:

