default:
  golem_name: rph.quiz
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
  mongodb_host: !expr Sys.getenv("MONGODB_HOST")
  mongodb_port: !expr Sys.getenv("MONGODB_PORT")
  mongodb_user: !expr Sys.getenv("MONGODB_USER")
  mongodb_pass: !expr Sys.getenv("MONGODB_PASS")
  mongodb_db: rphq
  mongodb_collection: answers
  mongodb_ca: /deploy_files/ca-certificate.crt
  mongodb_repset: !expr Sys.getenv("MONGODB_REPLICASET", "")
dev:
  golem_wd: !expr here::here()
  mongodb_host: 127.0.0.1
  mongodb_port: 12335
  mongodb_db: rphqdev
  mongodb_collection: answers
  mongodb_user: ""
  mongodb_pass: ""
